$color_active_border   = rgb({{colors.primary.default.hex_stripped}})
$color_inactive_border = rgb({{colors.surface_variant.default.hex_stripped}})
$color_secondary = rgb({{colors.secondary.default.hex_stripped}})
