# =============================================================================
# AUTOSTART
# =============================================================================

exec-once = /usr/lib/hyprland/hyprpolkitagent
exec-once = udiskie
exec-once = swww-daemon
exec-once = waybar
exec-once = swaync
exec-once = hypridle
exec-once = gsettings set org.gnome.desktop.interface color-scheme prefer-dark
exec-once = solaar -w hide
