# =============================================================================
# AUTOSTART
# =============================================================================

# Force workspaces onto correct monitors at startup
# HDMI-A-1 initialises first and grabs ws1 — we reassign immediately
exec-once = hyprctl dispatch moveworkspacetomonitor 1 DP-1
exec-once = hyprctl dispatch moveworkspacetomonitor 5 HDMI-A-1
exec-once = hyprctl dispatch workspace 1

exec-once = /usr/lib/hyprland/hyprpolkitagent
exec-once = udiskie
exec-once = swww-daemon
exec-once = waybar -c ~/.config/waybar/config-primary.jsonc -s ~/.config/waybar/style.css
exec-once = waybar -c ~/.config/waybar/config-secondary.jsonc -s ~/.config/waybar/style.css

exec-once = swaync
exec-once = hypridle
exec-once = gsettings set org.gnome.desktop.interface color-scheme prefer-dark
exec-once = solaar -w hide
