
#
# SOURCES
#


source = $HOME/.config/hypr/nvidia.conf
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/windowrules.conf
source = $HOME/.config/hypr/programs.conf
source = $HOME/.config/hypr/autostart.conf

#
# GENERAL
#

general {
	gaps_in = 5
	gaps_out = 10
	border_size = 2
	layout = master		# or: dwindle
}

#
# DECORATION
#

decoration {
	rounding = 8
	blur {
		enabled = true
		size = 6
		passes = 3
	}
	shadow {
		enabled = true
		range = 12
		color = rgba(0,0,0,0,4)
	}
}

#
# ANIMATIONS
#

animations {
	enabled = true
	bezier = ease, 0.4 0.0 0.2 1.0
	animation = windows, 1, 4, ease, slide
	animation = fade, 1, 4, ease
	animation = workspaces, 1, 5, ease, slide
}

#
# INPUT
#

input {
	kb_layout = se
	follow_mouse = 1
	sensitivity = 0
}

#
# LAYOUT SETTINGS
#

master {
	new_status = master
	new_on_top = true
	mfact = 0.55
}

dwindle {
	pseudotile = true
	preserve_split = true
}

#
# MISC
#

misc {
	force_default_wallpaper = 0
	disable_hyprland_logo = true
}


