$srcPath    = ~/.config/hypr/hyprlock/
$scriptPath = ~/.config/hypr/hyprlock/scripts/
$imgPath    = ~/.config/hypr/hyprlock/images/
$wallpapers = ~/pictures/wallpapers/

general {
    # no_fade_in = false              # Enable smooth fade-in animation
    grace = 0                       # Grace period before requiring password
    disable_loading_bar = false     # Show loading indicator
}

# Main display
background {
    monitor = DP-1
    path = $wallpapers/wp_16-9.png   
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

# Secondary display
background {
    monitor = HDMI-A-1
    path = $wallpapers/wp_9-16.png
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

image {
    monitor = DP-1
    path = $imgPath/profile.png
    border_size = 2
    border_color = rgba(255, 255, 255, 0)
    size = 160
    rounding = -1                   # -1 for perfect circle
    rotate = 0
    reload_time = -1
    reload_cmd =
    position = 0, 40
    halign = center
    valign = center
}

label {
    monitor = DP-1
    text = cmd[update:1000] echo -e "$(LC_TIME=en_US.UTF-8 date +"%A, %B %d")"
    color = rgba(216, 222, 233, 0.90)
    font_size = 25
    font_family = SF Pro Display Semibold
    position = 0, 350
    halign = center
    valign = center
}

label {
    monitor = DP-1
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(216, 222, 233, 0.90)
    font_size = 120
    font_family = SF Pro Display Bold
    position = 0, 230
    halign = center
    valign = center
}

shape {
    monitor = DP-1
    size = 280, 55
    color = rgba(255, 255, 255, .1)
    rounding = -1
    border_size = 0
    border_color = rgba(253, 198, 135, 0)
    rotate = 0
    xray = false
    position = 0, -130
    halign = center
    valign = center
}

label {
    monitor = DP-1
    text = $USER
    color = rgba(216, 222, 233, 0.80)
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    font_size = 18
    font_family = SF Pro Display Bold
    position = 0, -130
    halign = center
    valign = center
}


input-field {
    monitor = DP-1
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.2                 # Password dot size (0.2-0.8)
    dots_spacing = 0.2              # Spacing between dots (0.0-1.0)
    dots_center = true              # Center dots in field
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">Enter Pass</span></i>
    hide_input = false              # Show/hide password dots
    position = 0, -210
    halign = center
    valign = center
}

label {
    monitor = DP-1
    text = cmd[update:1000] echo "$($scriptPath/songdetail.sh)"
    color = rgba(255, 255, 255, 0.6)
    font_size = 18
    font_family = JetBrains Mono Nerd, SF Pro Display Bold
    position = 0, 50
    halign = center
    valign = bottom
}
