# =============================================================================
# SOURCES
# =============================================================================

source = ~/.config/hypr/hyprland/modules/nvidia.conf
source = ~/.config/hypr/hyprland/modules/monitors.conf
source = ~/.config/hypr/hyprland/modules/keybinds.conf
source = ~/.config/hypr/hyprland/modules/autostart.conf
source = ~/.cache/matugen/colors-hyprland.conf

# =============================================================================
# GENERAL
# =============================================================================

general {
    gaps_in = 2.5
    gaps_out = 5
    border_size = 1
    layout = dwindle     # can be set to: master or: dwindle — see tiling layout section below
    col.active_border = $color_active_border $color_secondary 45deg
    col.inactive_border = $color_inactive_border
}

# =============================================================================
# DECORATION
# =============================================================================

decoration {
    rounding = 5
    active_opacity = 1.0
    inactive_opacity = 1.0 
    blur {
        enabled = true
        size = 2
        passes = 3
        ignore_opacity = true
        xray = false
    }
    shadow {
        enabled = true
        range = 20
        color = rgba(0,0,0,0.9)
    }
}

# =============================================================================
# ANIMATIONS
# =============================================================================

animations {
    enabled = true
    bezier = ease, 0.4, 0.0, 0.2, 1.0
    animation = windows, 1, 4, ease, slide
    animation = fade, 1, 4, ease
    animation = workspaces, 1, 5, ease, slide
}

# =============================================================================
# INPUT
# =============================================================================

input {
    kb_layout = se
    numlock_by_default = true
    follow_mouse = 1
    # sensitivity = 0
    accel_profile = flat
    scroll_button_lock = true
    # scroll_method = on_button_down

    touchpad {
        natural_scroll = false
    }
}

# =============================================================================
# LAYOUT SETTINGS
# =============================================================================

master {
    new_status = master       # new window opens as master
    new_on_top = true
    mfact = 0.55              # master area takes 55% of screen width
}

dwindle {
    pseudotile = true
    preserve_split = true
}

# =============================================================================
# MISC
# =============================================================================

misc {
    force_default_wallpaper = 0    # disable Hyprland default wallpaper
    disable_hyprland_logo = true
}
